<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "regional_seo"
 *
 * Auto generated by Extension Builder 2016-03-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[ 'regional_seo' ] = [
    'title'            => 'Regional SEO',
    'description'      => 'Use hreflang for language and regional URLs (SEO)',
    'category'         => 'plugin',
    'author'           => 'Sebastian Iffland',
    'author_email'     => 'sebastian.iffland@ecom-ex.com',
    'state'            => 'stable',
    'internal'         => '',
    'uploadfolder'     => false,
    'createDirs'       => '',
    'clearCacheOnLoad' => false,
    'version'          => '7.6.4',
    'constraints'      => [
        'depends'   => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [
        ],
        'suggests'  => [
        ],
    ],
];