<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "regional_seo"
 *
 * Auto generated by Extension Builder 2016-03-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['regional_seo'] = array(
	'title' => 'regional URLs',
	'description' => 'Use hreflang for language and regional URLs (SEO)',
	'category' => 'plugin',
	'author' => 'Sebastian Iffland',
	'author_email' => 'sebastian.iffland@ecom-ex.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.6.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);